### ISSUE TITLE
Lokalizace

### ISSUE THREAD

**Issue by voglovaMiroslava** [voglovaMiroslava/CookBook#14]
Lokalizace alespoň do **tří jazyků**. Aktuální lokalizace bude zvolena podle nastavení operačního systému. V souladu s principem KISS se v žádném případě nesnažte přidat do konfigurace možnost uživatelského nastavení lokalizace; je to zbytečné a velmi by to zkomplikovalo kód aplikace.
## Tipy

V lokalizaci používejte default Locale, nenastavujte jej v kódu, aplikace se tak automaticky přizpůsobí uživatelovu nastavení OS. Pro vyzkoušení jiných locale je nejjednodušší přenastavit systémové properties nastavením parametrů při spuštění VM, např. pro americkou angličtinu "-Duser.language=en -Duser.country=US". V NetBeans se toto nastavení zadává v properties projektu v položce Run - VM Options, v IntelliJ IDEA se zadává v Run - Edit configurations - Configuration - VM options.

**Comment by voglovaMiroslava** [comment]
Přidána lokalizace do gui +default bundle. Nutno dodělat bundle pro cs, en a de.

**Comment by ghost** [comment]
přidán bundle pro cs_CZ a de_DE. Bundle pro en_EN už je v hotový
