### ISSUE TITLE
Návrh aplikace 2

### ISSUE THREAD

**Issue by voglovaMiroslava** [voglovaMiroslava/CookBook#2]
1.Vytvořte specifikaci pro vaši aplikaci a identifikujte případy užití. Případy užití modelujte prostřednictvím UML.
2.Vytvořte návrh aplikační vrstvy vaší aplikace a modelujte jej pomocí diagramu tříd v UML. Součástí návrhu zatím nebude návrh prezentační vrstvy ani uživatelského rozhraní

viz: https://is.muni.cz/auth/el/1433/jaro2016/PV168/um/ulohy/uloha1.html

**Comment by ghost** [comment]
1) Use case specifikace:
![usecase](https://cloud.githubusercontent.com/assets/11962962/13442607/5afdafa6-dffd-11e5-8e76-bd58db05aeab.png)

2) Class diagram:
![classdiagram](https://cloud.githubusercontent.com/assets/11962962/13442611/62f9258c-dffd-11e5-8450-2c8b9dc58ac5.png)

Vše v PDF:
[Cookbook_1.pdf](https://github.com/voglovaMiroslava/CookBook/files/153658/Cookbook_1.pdf)
