### ISSUE TITLE
Kostry tříd

### ISSUE THREAD

**Issue by voglovaMiroslava** [voglovaMiroslava/CookBook#5]
Vytvoření alespoň kostry všech tříd a jejich metod podle návrhu.

**Comment by ghost** [comment]
## 13.03.2016
- **Vytvořeny interfaci** pro RecipeManager, IngredientAmountManager a IngredientManager
- **Vytvořeny entitní třídy** Recipe, IngredientAmount a Ingredient - nejsou úplně dokonalé a v budoucnu je bude pravděpodobně nutné přepracovat
- **Vytvořeny kostry pro implementace** výše zmíněných interface tak, že **každá metoda vyhazuje NotImplementedException**, kromě **IngredientManagerImpl**, která je upravena tak, aby testy failovaly, ale nepadaly na chybách. **Ta samá úprava bude nutná i u další třídy, která bude testovaná**
