### ISSUE TITLE
Databázové operace

### ISSUE THREAD

**Issue by voglovaMiroslava** [voglovaMiroslava/CookBook#6]
Implementujte základní databázové operace (CRUD) alespoň pro jednu entitu.

Tipy: 
Tabulky v databázi nevytvářejte ručně, ale napište si na to SQL skript. Velice vám to usnadní život, protože budete v případě potřeby moci snadno tabulky založit znovu. To se hodí např. při stěhování na jiný počítač, kvůli ladění apod.
Používejte automaticky generované primární klíče. U JavaDB k tomu slouží klíčová slova GENERATED ALWAYS AS IDENTITY (viz příklad níže).
Skript na založení tabulek může vypadat např. takto:
CREATE TABLE GRAVE (
    ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    GRAVECOLUMN INTEGER,
    GRAVEROW INTEGER,
    CAPACITY INTEGER,
    NOTE VARCHAR(50)
 );

**Comment by ghost** [comment]
- Implementovány CRUD operace nad databází pro Ingredience - IngredientManagerImpl
- Přidán package daocontext spravující načítání a získávání datasource - konfigurovatelné přes soubor db-config.xml
- Upraveny testy pro IngredientManager tak, aby pracovaly s daocontext a datasourcem
